refresh_delay: 5

outputs:
  influx:
    url: "<URL>"
    token: "<TOKEN>"
    bucket: "<BUCKET>"
    organization: "<ORGANIZATION>"

topics: 
  - name: "/cmd_vel"
    measurements:
      - name: "cmd_vel"
        fields:
          - field: "linear_x"
            value: "$msg.linear.x"
          - field: "angular_z"
            value: "$msg.angular.z"